baseURL: "https://risanb.com/"
title: Risan Bagja Pradana
languageCode: en
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: dracula
imaging:
  quality: 80
params:
  description: My name is Risan Bagja Pradana and I love playing with the computer. This website is an archive of my thoughts. I blog about programming stuff, my daily life, my traveling experiences, and other random things.
  images: [/img/risan-og.jpg]
  cloudflareAnalytics: aeac8266c43a442d9d54081840ad9b3a

