baseurl = ""
title = "rachel's blog"
languageCode = "en-us"
publishDir = 'docs'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'dracula'

[imaging]
  quality = 80

[params]
  header_image = "images/main_go_wideandtall_darklayer.jpeg"
  title = "Software Engineering"
  SEOTitle = "software engineering blog"
  keyword = "software engineering, blog, job search"
  image_404 = "img/404-bg.jpg"
  title_404 = "We couldn't find what you were looking for..."
  description = "My name is Rachel Ombok, hello! I blog about programming and non-programming stuff."
  images = "/about/biopic6.jpg"
